name: dml_proj_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - aiohappyeyeballs=2.4.0=py39haa95532_0
  - aiohttp=3.10.5=py39h827c3e9_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - arrow-cpp=16.1.0=h7cd61ee_0
  - async-timeout=4.0.3=py39haa95532_0
  - attrs=24.2.0=py39haa95532_0
  - aws-c-auth=0.6.19=h2bbff1b_0
  - aws-c-cal=0.5.20=h2bbff1b_0
  - aws-c-common=0.8.5=h2bbff1b_0
  - aws-c-compression=0.2.16=h2bbff1b_0
  - aws-c-event-stream=0.2.15=hd77b12b_0
  - aws-c-http=0.6.25=h2bbff1b_0
  - aws-c-io=0.13.10=h2bbff1b_0
  - aws-c-mqtt=0.7.13=h2bbff1b_0
  - aws-c-s3=0.1.51=h2bbff1b_0
  - aws-c-sdkutils=0.1.6=h2bbff1b_0
  - aws-checksums=0.1.13=h2bbff1b_0
  - aws-crt-cpp=0.18.16=hd77b12b_0
  - aws-sdk-cpp=1.10.55=hd77b12b_0
  - blas=1.0=mkl
  - boost-cpp=1.82.0=h59b6b97_2
  - bottleneck=1.3.7=py39h9128911_0
  - brotli-python=1.0.9=py39hd77b12b_8
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.19.1=h2bbff1b_0
  - ca-certificates=2024.9.24=haa95532_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=py39haa95532_0
  - datasets=3.0.1=pyhd8ed1ab_0
  - dill=0.3.8=py39haa95532_0
  - filelock=3.13.1=py39haa95532_0
  - frozenlist=1.4.0=py39h2bbff1b_0
  - fsspec=2024.3.1=py39haa95532_0
  - gflags=2.2.2=hd77b12b_1
  - glog=0.5.0=hd77b12b_1
  - gmpy2=2.1.2=py39h7f96b67_0
  - huggingface_hub=0.24.6=py39haa95532_0
  - idna=3.7=py39haa95532_0
  - importlib-metadata=7.0.1=py39haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jinja2=3.1.4=py39haa95532_0
  - libabseil=20240116.2=cxx17_h5da7b33_0
  - libboost=1.82.0=h3399ecb_2
  - libbrotlicommon=1.0.9=h2bbff1b_8
  - libbrotlidec=1.0.9=h2bbff1b_8
  - libbrotlienc=1.0.9=h2bbff1b_8
  - libcurl=8.9.1=h0416ee5_0
  - libevent=2.1.12=h56d1f94_1
  - libgrpc=1.62.2=hf25190f_0
  - libprotobuf=4.25.3=hf2fb9eb_0
  - libssh2=1.11.0=h291bd65_0
  - libthrift=0.15.0=h4364b78_2
  - libuv=1.48.0=h827c3e9_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=2.1.3=py39h2bbff1b_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py39h2bbff1b_1
  - mkl_fft=1.3.10=py39h827c3e9_0
  - mkl_random=1.2.7=py39hc64d2fc_0
  - mpc=1.1.0=h7edee0f_1
  - mpfr=4.0.2=h62dcd97_1
  - mpir=3.0.0=hec2e145_1
  - mpmath=1.3.0=py39haa95532_0
  - multidict=6.0.4=py39h2bbff1b_0
  - multiprocess=0.70.15=py39haa95532_0
  - networkx=3.2.1=py39haa95532_0
  - numexpr=2.8.7=py39h2cd9be0_0
  - numpy=1.26.4=py39h055cbcc_0
  - numpy-base=1.26.4=py39h65a83cf_0
  - openssl=3.3.2=h2466b09_0
  - orc=2.0.1=hd8d391b_0
  - packaging=24.1=py39haa95532_0
  - pandas=2.2.2=py39h5da7b33_0
  - pip=24.2=py39haa95532_0
  - pyarrow=16.1.0=py39hc64d2fc_0
  - pysocks=1.7.1=py39haa95532_0
  - python=3.9.20=h8205438_1
  - python-dateutil=2.9.0post0=py39haa95532_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python-xxhash=2.0.2=py39h2bbff1b_1
  - pytz=2024.1=py39haa95532_0
  - pyyaml=6.0.2=py39h827c3e9_0
  - re2=2022.04.01=hd77b12b_0
  - regex=2024.9.11=py39h827c3e9_0
  - requests=2.32.3=py39haa95532_0
  - safetensors=0.4.4=py39h9e6c545_0
  - setuptools=75.1.0=py39haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.2.1=hcdb6601_0
  - sqlite=3.45.3=h2bbff1b_0
  - tbb=2021.8.0=h59b6b97_0
  - tokenizers=0.19.1=py39h7ac788d_0
  - tqdm=4.66.5=py39h9909e9c_0
  - transformers=4.44.1=py39haa95532_0
  - typing-extensions=4.11.0=py39haa95532_0
  - typing_extensions=4.11.0=py39haa95532_0
  - tzdata=2024b=h04d1e81_0
  - ucrt=10.0.22621.0=h57928b3_1
  - urllib3=2.2.3=py39haa95532_0
  - utf8proc=2.6.1=h2bbff1b_1
  - vc=14.40=h2eaa2aa_1
  - vc14_runtime=14.40.33810=hcc2c482_22
  - vs2015_runtime=14.40.33810=h3bf8584_22
  - wheel=0.44.0=py39haa95532_0
  - win_inet_pton=1.1.0=py39haa95532_0
  - xxhash=0.8.0=h2bbff1b_3
  - xz=5.4.6=h8cc25b3_1
  - yaml=0.2.5=he774522_0
  - yarl=1.11.0=py39h827c3e9_0
  - zipp=3.20.2=py39haa95532_0
  - zlib=1.2.13=h8cc25b3_1
  - zstd=1.5.6=h8880b57_0
  - pip:
      - accelerate==1.0.1
      - audioread==3.0.1
      - cffi==1.17.1
      - contourpy==1.3.0
      - cycler==0.12.1
      - decorator==5.1.1
      - evaluate==0.4.3
      - fonttools==4.54.1
      - importlib-resources==6.4.5
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - librosa==0.10.2.post1
      - llvmlite==0.43.0
      - matplotlib==3.9.2
      - msgpack==1.1.0
      - numba==0.60.0
      - pillow==11.0.0
      - platformdirs==4.3.6
      - pooch==1.8.2
      - psutil==6.1.0
      - pycparser==2.22
      - pydub==0.25.1
      - pyparsing==3.2.0
      - scikit-learn==1.5.2
      - scipy==1.13.1
      - soundfile==0.12.1
      - soxr==0.5.0.post1
      - sympy==1.13.1
      - threadpoolctl==3.5.0
prefix: C:\Users\skhan\miniconda3\envs\dml_proj_env
